### ISSUE TITLE
trouble with dwapi after upgrade

### ISSUE THREAD

**Issue by cmullah** [palladiumkenya/dwapi#90]
after upgrading dwapi using the commads in the dwapi page i couldnt access it again and this is what the browser was displaying,kindly assist
![WhatsApp Image 2020-09-11 at 8 17 57 AM](https://user-images.githubusercontent.com/71116782/92868112-0b9e5e80-f40a-11ea-950e-e67c2df4e704.jpeg)

**Comment by koskedk** [comment]
kindly upgrade to latest version.
